---
- name: "sites-available"
  sudo: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ server_hostname }}
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: "sites-enabled"
  sudo: yes
  file:
    state: link
    src: /etc/nginx/sites-available/{{ server_hostname }}
    dest: /etc/nginx/sites-enabled/{{ server_hostname }}
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: "directory"
  sudo: yes
  file:
    state: directory
    path: /var/www/{{ server_hostname }}
    owner: www-data
    group: www-data
    mode: 0775
  notify: reload nginx

- name: "files"
  sudo: no
  remote_user: trooney
  synchronize:
    src: ../dist/
    dest: /var/www/{{ server_hostname }}
    archive: no
    recursive: true
    
